# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - zenith-portal-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Install production dependencies only
        run: npm install --production

      - name: Copy the updated server.js to the standalone folder
        run: cp server.js .next/standalone/server.js

      - name: Copy public folder into standalone
        run: cp -r public .next/standalone

      - name: Move .next/static to wwwroot
        run: |
          mkdir -p .next/standalone/_next/static
          cp -r .next/static .next/standalone/_next/

      - name: Zip build output and runtime files
        run: |
          zip -r release.zip .next/standalone package.json next.config.js package-lock.json startup.sh

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # required for requesting JWT
      contents: read # required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d app



      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1492851337B2474C82C63C6F6EAA3248 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C89018ADED634D46A6B105BD9BF4E499 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F0E4AC1C01104BF881431788A56FF4FB }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'zenith-portal-web'
          slot-name: 'Production'
          package: ./app

          
