# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - zenith-portal-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Match your project's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build  
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_912F094FA413493FB451734309D81685 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9A98EFD00EE94E41B3F4021FB2C33121 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E54F057E3488453F80B16C74A882CFA8 }}

      - name: Zip files preserving symlinks
        run: |
         zip -r deploy.zip .next node_modules package.json public next.config.js

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'zenith-portal-web'
          slot-name: 'Production'
          package: .
          
